version: '3'
services:
  nginx:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Map your local nginx.conf to the container
    networks:
      - mynetwork

networks:
  mynetwork:
    external:
      name: mynetwork  # Reference the external network by name

