version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    external:
      name: mynetwork  # Reference the external network by name
